-- trigger on updating email
DELIMITER $$
DROP TRIGGER IF EXISTS USERS_AFTER_INSERT;
CREATE TRIGGER USERS_BEFORE_INSERT
	BEFORE UPDATE ON users
	FOR EACH ROW
BEGIN
	IF NEW.email != OLD.email THEN
		SET NEW.valid_email = 0;
	END IF;
END$$

DELIMITER ;
